language: java #language
jdk:
    - openjdk8   #VM
    
cache:
    directories:
        - "$HOME/.cache"

    
jobs:
    - stage: deploy #stage type
      name: "Deploy To Dev Environment" #stage name
      script:
       - mvn clean install #job-1
       - cp .travis.settings.xml $HOME/.m2/settings.xml
       - mvn deploy -DmuleDeploy -Dserver=$server -Dworkers=$workers -DworkerType=$workerType -Denvironment=$environment -DmuleVersion=$muleVersion -DappName=$appName
      if: branch = master #specify which branch to build
    